### PR TITLE
Fix openssl issue

### LINKED ISSUE #31: Add sudo to openssl command to get around permissions issue
The following errors are happening during openssl CA certificate creation.
```
null_resource.anthos_deploy_cluster[0] (remote-exec): null_resource.anthos_deploy_cluster (remote-exec): Can't load /home/ubuntu/.rnd into RNG
null_resource.anthos_deploy_cluster[0] (remote-exec): null_resource.anthos_deploy_cluster (remote-exec): 140461474767296:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/ubuntu/.rnd
```
There are some openssl issues and it looks like this is a permissions issues according to: https://github.com/openssl/openssl/issues/7754

I think updating the following line From:
https://github.com/packet-labs/google-anthos/blob/40af0e953984c6a735b3e0bcf9c39e36f7af6176/anthos/cluster/finish_cluster.sh#L22

To:
```bash
sudo openssl \
```
 Will solve the issue.

### PR DESCRIPTION
**Pull request by c0dyhi11**
fixes #31 

Simply added `sudo` to the `openssl` line

### CODE REVIEW

**Comment by paemason** [comment]
Thanks for jumping on this. I'm going to take a closer look because this step is quite finicky. I want to make sure we can work with the key after it's created via sudo or if we need to set the user ubuntu to owner first.

**Comment by paemason** [comment]
Confirmed that creating the cert under sudo would create an issue accessing the cert when we tried to apply it to the cluster. Added the fix and doing a full test now.

**Comment by paemason** [comment]
Even with sudo, we still see the error:
```
null_resource.anthos_deploy_cluster[0] (remote-exec): null_resource.anthos_deploy_cluster (remote-exec): Can't load /home/ubuntu/.rnd into RNG
null_resource.anthos_deploy_cluster[0] (remote-exec): null_resource.anthos_deploy_cluster (remote-exec): 140045770285504:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/ubuntu/.rnd
```

**Comment by c0dyhi11** [comment]
I say we kill this PR then.

**Comment by c0dyhi11** [comment]
Killing

**Pull request closed without merging**
