### PR TITLE
Fix issue 8.

### PR DESCRIPTION
**Pull request by boredabdel**
Allow people to bring their existing packet project. Added some documentation

### CODE REVIEW

**Comment by paemason** [comment]
looks like it would do the trick. I'm wondering if using a conditional each time we reference the project id can be streamlined. 

Something like adding the following into 01-create-project.tf

```
resource "packet_project_id" "packet_project_id" {
    depends_on = [packet_project.new_project]
    id = var.create_project ? packet_project.new_project[0].id : var.project_id
}
```
Then we can just refer to `packet_project_id.packet_project_id.id` each time instead of the conditional.

I'm not 100% sure this would work. @c0dyhi11 do you have any thoughts/suggestions?

**Comment by c0dyhi11** [comment]
This can be done with local variables. We do the condition once and set the project ID either after create or if it’s passed in. Then you can use the local variable every time after that. 

https://www.terraform.io/docs/configuration/locals.html

**Comment by paemason** [comment]
@boredabdel could you look at Cody's recommendation and use local variables rather the conditional each time?

**Comment by boredabdel** [comment]
Hi, Sorry for the delay, will work on this today :)

**Comment by paemason** [comment]
I needed to integrate your code and use the local variable to complete some work I am doing on the SSH key. I'm going to close this PR and open a new one when my testing is complete.

**Pull request closed without merging**
